// Questions spécifiques à la leçon des jours de la semaine
const quizData = [
  {
    question: "  ماذا قَالَ الْوَلَدُ لِلتَّحِيَّةِ؟ ",
    image: "",
    a: "السَّلامُ عَلَيْكُمْ",
    b: "مَساءُ الْخَيْرْ",
    c: "وَعَلَيْكُمُ السَّلامُ",
    d: "صَباحُ الْخَيْرِ",
    correct: "a",
    questionSound: "../audio/dialogue1/question1.MP3",
    sounds: {
      a: "../audio/dialogue1/salam.MP3",
      b: "../audio/dialogue1/massa.MP3",
      c: "../audio/dialogue1/alikoum.MP3",
      d: "../audio/dialogue1/sabah.MP3",
    },
  },
  {
    question: " مَا اسْمُ الْوَلَدْ؟   ",
    image: "",
    a: "رَيانْ",
    b: "فَاطِمَة",
    c: "خَالِد",
    d: "عَلِيُّ",
    correct: "d",
    questionSound: "../audio/dialogue1/masmo.MP3",
    sounds: {
      a: "../audio/dialogue1/rayan.MP3",
      b: "../audio/dialogue1/fatima.MP3",
      c: "../audio/dialogue1/khalid.MP3",
      d: "../audio/dialogue1/ali.MP3",
    },
  },
  {
    question: " مَا اسْمُ الْبِنْتْ؟  ",
    image: "../images/vocabulaire/1.jpg",
    a: "دِينَا",
    b: "فَاطِمَة",
    c: "سَلْمى",
    d: "عَلِيُّ",
    correct: "b",
    questionSound: "../audio/dialogue1/masmobint.MP3",
    sounds: {
      a: "../audio/dialogue1/dina.MP3",
      b: "../audio/dialogue1/fatima.MP3",
      c: "../audio/dialogue1/salma.MP3",
      d: "../audio/dialogue1/ali.MP3",
    },
  },

  {
    question: "   كَمْ عُمْرُ الْوَلَدْ؟   ",
    image: "../images/vocabulaire/1.jpg",
    a: "تِسْعُ سَنَوَاتْ",
    b: "عَشْرُ سَنَوَاتْ",
    c: "ثَمَانِي سَنَوَاتْ",
    d: "سَبْعُ سَنَوَاتْ",
    correct: "b",
    questionSound: "../audio/dialogue1/kamwalad.MP3",
    sounds: {
      a: "../audio/dialogue1/tis3o.MP3",
      b: "../audio/dialogue1/3achro.MP3",
      c: "../audio/dialogue1/tamanis.MP3",
      d: "../audio/dialogue1/sab3os.MP3",
    },
  },
  {
    question: "أَيْنَ وُلِدَ الْوَلَدُ؟  ",
    image: "",
    a: "تُونُسْ",
    b: "داكار",
    c: "الْرِّبَاطْ",
    d: "الْجَزَائِرْ",
    correct: "c",
    questionSound: "../audio/dialogue1/aynawolidawalad.MP3",
    sounds: {
      a: "../audio/dialogue1/tounos.MP3",
      b: "../audio/dialogue1/dakar.MP3",
      c: "../audio/dialogue1/rabat.MP3",
      d: "../audio/dialogue1/alger.MP3",
    },
  },
  {
    question: " أَيْنَ وُلِدَتِ الْبِنْتُ؟ ",
    image: "",
    a: "بَاماكو",
    b: "تُونُسْ",
    c: "الْجَزَائِرْ",
    d: "أَبِيدْجَانْ",
    correct: "c",
    questionSound: "../audio/dialogue1/aynawolidabint.MP3",
    sounds: {
      a: "../audio/dialogue1/bamako.MP3",
      b: "../audio/dialogue1/tounos.MP3",
      c: "../audio/dialogue1/alger.MP3",
      d: "../audio/dialogue1/abidjan.MP3",
    },
  },
  {
    question: " أَيْنَ يَسْكُنُ الْوَلَدُ والْبِنْتُ؟  ",
    image: "",
    a: "نِيسْ",
    b: "قَارِسْ",
    c: "بَاريسْ",
    d: "لِيلْ",
    correct: "c",
    questionSound: "../audio/dialogue1/aynayaskono.MP3",
    sounds: {
      a: "../audio/dialogue1/nice.MP3",
      b: "../audio/dialogue1/karis.MP3",
      c: "../audio/dialogue1/paris.MP3",
      d: "../audio/dialogue1/lile.MP3",
    },
  },
];
